project:
  type: website
  pre-render: scripts/on_render/gen_index.R
  render: 
    - "*.qmd"
    - "!tutorials/drafts/" #don't attempt to render the drafts folder
    - "!workbooks/" # don't attempt to render the workbooks

website:
  title: R Training
  navbar:
    # Sussex Flint
    background: "#003b49"
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Tutorials"
        file: tutorials.qmd
      - text: "Workshops"
        file: workshops.qmd
    right:
      - href: https://canvas.sussex.ac.uk/courses/29761
        text: "Canvas"
      - text: "About"
        file: about.qmd

  sidebar: 
    - title: "Tutorials"
      style: "docked"
      # Sussex Cool Grey
      # https://www.sussex.ac.uk/brand/designers/colour
      background: "#d0d3d4"
      contents: 
        - tutorials.qmd
        - quick_ref.qmd
        - data_workbooks.qmd
        - section: "FundRmentals"
          contents:
            - auto: tutorials/psychrlogy/01_fundRmentals/*
        - section: "Essentials"
          contents:
            - auto: tutorials/psychrlogy/02_essentials/*
        - section: "ImprovRs"
          contents:
            - auto: tutorials/psychrlogy/03_improvRs/*
    - title: "Workshops"
      contents:
        - Workshops.qmd
  page-footer: 
    center: "&copy; Jennifer Mankin 2023"
    background: "#003b49"
    
format:
  html:
    theme: 
      light: [flatly, theme-flatly.scss]
      # https://quarto.org/docs/output-formats/html-themes.html#theme-options
      dark: [darkly, theme-darkly.scss]
    css: styles.css
    toc: true
    toc-depth: 4
    embed-resources: true
    code-overflow: wrap
    code-block-bg: true
    #code-block-border-left: "#be84a3"
    highlight-style: 
      light: tomorrow
      
      dark: cobalt
    df-print: paged

editor: visual

execute:
  warning: false
  message: false