project:
  type: website
  pre-render: scripts/on_render/gen_index.R
  render: 
    - "*.qmd"
    - "!tutorials/drafts/" #don't attempt to render the drafts folder
    - "!tutorials/staff/" #don't attempt to render the staff folder
    - "!workbooks/" # don't attempt to render the workbooks
    # - "!tutorials/archive_autumn_2023/"

website:
  title: R Training
  navbar:
    # Sussex Flint
    background: "#003b49"
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Tutorials"
        file: tutorials.qmd
      - text: "Workshops"
        file: workshops.qmd
      - text: "Resources"  
        file: resources.qmd
    right:
      - href: https://canvas.sussex.ac.uk/courses/29761
        text: "Canvas"
      - text: "About"
        file: about.qmd

  sidebar: 
    - title: "Tutorials"
      style: "docked"
      # Sussex Cool Grey
      # https://www.sussex.ac.uk/brand/designers/colour
      background: "#d0d3d4"
      contents: 
        - tutorials.qmd
        - quick_ref.qmd
        - section: "Current"
          contents:
            - auto: tutorials/docs/*
        - section: "Archive (Autumn 2023)"
          contents:
            - auto: tutorials/archive_autumn_2023/*
    - title: "Workshops"
      style: "docked"
      background: "#d0d3d4"
      contents:
        - workshops.qmd
        - section: "Dissertations"
          contents:
            - auto: workshops/dissertations/*
    - title: "Resources"
      style: "docked"      
      background: "#d0d3d4"
      contents:
        - resources.qmd
        - data_workbooks.qmd
        - section: "FAQs"
          contents:
            - auto: resources/faqs/*
  page-footer: 
    center: "&copy; Jennifer Mankin 2024"
    background: "#003b49"
    
format:
  html:
    theme: 
      light: [flatly, theme-flatly.scss]
      # https://quarto.org/docs/output-formats/html-themes.html#theme-options
      dark: [darkly, theme-darkly.scss]
    css: styles.css
    toc: true
    toc-depth: 4
    # This bastard caused the rendering issues - DO NOT DO THIS AGAIN
    # embed-resources: true
    code-overflow: wrap
    code-block-bg: true
    # Forces embed code blocks out of alignment
    #code-block-border-left: "#be84a3"
    df-print: paged
    fig-align: center

## Can't get this to work but the default is fine I guess
# highlight-style: 
#   light: tomorrow
#   dark: cobalt

editor: source

execute:
  warning: false
  message: false