---
title: 'Data and Workbooks'
---


## Datasets


Download and save datasets to use for tutorial tasks here.
Either copy the link to use in a reading-in function (e.g. `readr::read_csv()`, `haven::read_sav()`), or save the data at the link to a file to read in.
Make sure that if you save the file, you keep the correct file suffix!


<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Filename </th>
   <th style="text-align:left;"> Citation/Source </th>
   <th style="text-align:left;"> Comments </th>
   <th style="text-align:left;"> Download </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> anx_data.csv </td>
   <td style="text-align:left;"> <a href="https://osf.io/8jk5v/">Terry, Lea, &amp; Field (in prep)</a> </td>
   <td style="text-align:left;"> Dataset shared for teaching purposes. Note that demographics in this dataset are SIMULATED FOR TEACHING PURPOSES and are NOT real data. </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/data/anx_data.csv">Download anx_data.csv</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> anx_scores_data.csv </td>
   <td style="text-align:left;"> <a href="https://osf.io/8jk5v/">Terry, Lea, &amp; Field (in prep)</a> </td>
   <td style="text-align:left;"> Dataset shared for teaching purposes, with mean subscale scores instead of individual items. Note that demographics in this dataset are SIMULATED FOR TEACHING PURPOSES and are NOT real data. </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/data/anx_scores_data.csv">Download anx_scores_data.csv</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> bp_data.csv </td>
   <td style="text-align:left;"> <a href="https://sussex.figshare.com/articles/dataset/Dataset_for_paper_Body_Positivity_but_not_for_everyone/9885644">Simon &amp; Hurst (2021)</a> </td>
   <td style="text-align:left;"> Dataset publicly available. Note that this subset of the public data has had ID variables and missing values randomly introduced for teaching purposes. </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/data/bp_data.csv">Download bp_data.csv</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> mil_data.sav </td>
   <td style="text-align:left;"> <a href="https://profiles.sussex.ac.uk/p323096-vlad-costin">Eldarwish et al., (in prep)</a> </td>
   <td style="text-align:left;"> Dataset expected to be publicly available in the future. Note that this dataset is entirely simulated, based on existing real data. </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/data/mil_data.sav">Download mil_data.sav</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> mil_data_wkshp.sav </td>
   <td style="text-align:left;"> <a href="https://profiles.sussex.ac.uk/p323096-vlad-costin">Eldarwish et al., (in prep)</a> </td>
   <td style="text-align:left;"> Version of mil_data.sav with additional simulated variables for workshop use, contributed by Dr Dan Evans </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/data/mil_data_wkshp.sav">Download mil_data_wkshp.sav</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> syn_data.csv </td>
   <td style="text-align:left;"> <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0155483">Mealor et al., 2016</a> </td>
   <td style="text-align:left;"> Dataset publicly available </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/data/syn_data.csv">Download syn_data.csv</a> </td>
  </tr>
</tbody>
</table>


## Workbooks

Right-click the link below and choose Save link as... to save as a .Qmd,
or click through to view the text and copy/paste into an empty .Qmd document.

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Tutorial/Workshop Name </th>
   <th style="text-align:left;"> Download </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 01/02: IntRoduction </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/workbooks/01_02_intro_workbook.qmd" download="01_02_intro_workbook.qmd">Download 01_02_intro_workbook.qmd</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 03: Datasets </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/workbooks/03_datasets_workbook.qmd" download="03_datasets_workbook.qmd">Download 03_datasets_workbook.qmd</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 04: Reporting Linear Models with Quarto </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/workbooks/04_lm_workbook.qmd" download="04_lm_workbook.qmd">Download 04_lm_workbook.qmd</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 05: Filter and Select </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/workbooks/05_filter_workbook.qmd" download="05_filter_workbook.qmd">Download 05_filter_workbook.qmd</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 06: Mutate and Summarise </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/workbooks/06_changes_workbook.qmd" download="06_changes_workbook.qmd">Download 06_changes_workbook.qmd</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 07: Visualisations </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/workbooks/07_dataviz_workbook.qmd" download="07_dataviz_workbook.qmd">Download 07_dataviz_workbook.qmd</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 08: Analysis </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/workbooks/08_analysis_workbook.qmd" download="08_analysis_workbook.qmd">Download 08_analysis_workbook.qmd</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 09: Test Flight </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/workbooks/09_testflight_workbook.qmd" download="09_testflight_workbook.qmd">Download 09_testflight_workbook.qmd</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 10: Qualtrics and Labelled Data </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/workbooks/10_qtrics_workbook.qmd" download="10_qtrics_workbook.qmd">Download 10_qtrics_workbook.qmd</a> </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Working with Qualtrics Data </td>
   <td style="text-align:left;"> <a href="https://raw.githubusercontent.com/drmankin/practicum/master/workbooks/qualtrics_workshop_workbook.qmd" download="qualtrics_workshop_workbook.qmd">Download qualtrics_workshop_workbook.qmd</a> </td>
  </tr>
</tbody>
</table>
