---
title: 'Quick Reference'
---

## Index of Topics

If you're looking for a particular section of a tutorial, use this handy summary to jump straight to the section you want.

<table class="table table-condensed table" style="margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;text-align: center;"> Topic </th>
   <th style="text-align:left;text-align: center;"> Sub-Topic </th>
  </tr>
 </thead>
<tbody>
  <tr grouplength="6"><td colspan="2" style="border-bottom: 1px solid;"><strong>01: IntRoduction</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Orientation](tutorials/docs/01_intro.qmd#orientation) </td>
   <td style="text-align:left;"> [R is for Reproducibility](tutorials/docs/01_intro.qmd#r-is-for-reproducibility), [Using the Tutorials](tutorials/docs/01_intro.qmd#using-the-tutorials), [The RStudio Interface](tutorials/docs/01_intro.qmd#the-rstudio-interface) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Errors](tutorials/docs/01_intro.qmd#errors) </td>
   <td style="text-align:left;"> [GlossoRlia: the Language of Errors](tutorials/docs/01_intro.qmd#glossorlia:-the-language-of-errors) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Types of Data](tutorials/docs/01_intro.qmd#types-of-data) </td>
   <td style="text-align:left;"> [Numeric Data](tutorials/docs/01_intro.qmd#numeric-data), [Character Data](tutorials/docs/01_intro.qmd#character-data), [Factor Data](tutorials/docs/01_intro.qmd#factor-data), [Logical Data](tutorials/docs/01_intro.qmd#logical-data) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Class and Coercion](tutorials/docs/01_intro.qmd#class-and-coercion) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Objects](tutorials/docs/01_intro.qmd#objects) </td>
   <td style="text-align:left;"> [Creating an Object](tutorials/docs/01_intro.qmd#creating-an-object), [Naming Objects](tutorials/docs/01_intro.qmd#naming-objects), [Calling an Object](tutorials/docs/01_intro.qmd#calling-an-object), [Using Objects](tutorials/docs/01_intro.qmd#using-objects), [Overwriting Objects](tutorials/docs/01_intro.qmd#overwriting-objects) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Quick Test: *t*-test](tutorials/docs/01_intro.qmd#quick-test:-*t*-test) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="5"><td colspan="2" style="border-bottom: 1px solid;"><strong>02: IntRoduction II</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Setup](tutorials/docs/02_intro.qmd#setup) </td>
   <td style="text-align:left;"> [Projects](tutorials/docs/02_intro.qmd#projects), [Documents](tutorials/docs/02_intro.qmd#documents) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Packages](tutorials/docs/02_intro.qmd#packages) </td>
   <td style="text-align:left;"> [Loading `tidyverse`](tutorials/docs/02_intro.qmd#loading-`tidyverse`) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Functions](tutorials/docs/02_intro.qmd#functions) </td>
   <td style="text-align:left;"> [Basics and Help](tutorials/docs/02_intro.qmd#basics-and-help), [Arguments](tutorials/docs/02_intro.qmd#arguments), [Using Functions](tutorials/docs/02_intro.qmd#using-functions), [Passing Multiple Values to Arguments](tutorials/docs/02_intro.qmd#passing-multiple-values-to-arguments) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Packages Revisited](tutorials/docs/02_intro.qmd#packages-revisited) </td>
   <td style="text-align:left;"> [Installing Packages](tutorials/docs/02_intro.qmd#installing-packages), [Loading Packages](tutorials/docs/02_intro.qmd#loading-packages) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Exercises](tutorials/docs/02_intro.qmd#exercises) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="9"><td colspan="2" style="border-bottom: 1px solid;"><strong>03: Datasets</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Setup](tutorials/docs/03_datasets.qmd#setup) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Reading In](tutorials/docs/03_datasets.qmd#reading-in) </td>
   <td style="text-align:left;"> [File Types](tutorials/docs/03_datasets.qmd#file-types), [From File](tutorials/docs/03_datasets.qmd#from-file), [From URL](tutorials/docs/03_datasets.qmd#from-url) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Codebook](tutorials/docs/03_datasets.qmd#codebook) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Viewing](tutorials/docs/03_datasets.qmd#viewing) </td>
   <td style="text-align:left;"> [Call the Object](tutorials/docs/03_datasets.qmd#call-the-object), [A Glimpse of the Data](tutorials/docs/03_datasets.qmd#a-glimpse-of-the-data), [View Mode](tutorials/docs/03_datasets.qmd#view-mode) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Overall Summaries](tutorials/docs/03_datasets.qmd#overall-summaries) </td>
   <td style="text-align:left;"> [Basic Summary](tutorials/docs/03_datasets.qmd#basic-summary), [Other Summaries](tutorials/docs/03_datasets.qmd#other-summaries) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [The Pipe](tutorials/docs/03_datasets.qmd#the-pipe) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Describing Datasets](tutorials/docs/03_datasets.qmd#describing-datasets) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Describing Variables](tutorials/docs/03_datasets.qmd#describing-variables) </td>
   <td style="text-align:left;"> [Counting](tutorials/docs/03_datasets.qmd#counting), [Subsetting](tutorials/docs/03_datasets.qmd#subsetting), [Descriptives](tutorials/docs/03_datasets.qmd#descriptives), [Visualisations](tutorials/docs/03_datasets.qmd#visualisations) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Exercises](tutorials/docs/03_datasets.qmd#exercises) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="6"><td colspan="2" style="border-bottom: 1px solid;"><strong>04: Filter and Select</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Setup](tutorials/docs/04_filter.qmd#setup) </td>
   <td style="text-align:left;"> [Packages](tutorials/docs/04_filter.qmd#packages), [Data](tutorials/docs/04_filter.qmd#data) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Thinking Like a Coder](tutorials/docs/04_filter.qmd#thinking-like-a-coder) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Filter](tutorials/docs/04_filter.qmd#filter) </td>
   <td style="text-align:left;"> [General Format](tutorials/docs/04_filter.qmd#general-format), [Single Assertions](tutorials/docs/04_filter.qmd#single-assertions), [Multiple Assertions](tutorials/docs/04_filter.qmd#multiple-assertions), [Exercises](tutorials/docs/04_filter.qmd#exercises), [Data Cleaning](tutorials/docs/04_filter.qmd#data-cleaning) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Select](tutorials/docs/04_filter.qmd#select) </td>
   <td style="text-align:left;"> [General Format](tutorials/docs/04_filter.qmd#general-format), [Selecting Directly](tutorials/docs/04_filter.qmd#selecting-directly), [Using tidyselect](tutorials/docs/04_filter.qmd#using-tidyselect), [Using Functions](tutorials/docs/04_filter.qmd#using-functions) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Exporting](tutorials/docs/04_filter.qmd#exporting) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Quick Test](tutorials/docs/04_filter.qmd#quick-test) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="10"><td colspan="2" style="border-bottom: 1px solid;"><strong>05: Mutate</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Setup](tutorials/docs/05_mutate.qmd#setup) </td>
   <td style="text-align:left;"> [Packages](tutorials/docs/05_mutate.qmd#packages), [Data](tutorials/docs/05_mutate.qmd#data) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [General Format](tutorials/docs/05_mutate.qmd#general-format) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Adding New Variables](tutorials/docs/05_mutate.qmd#adding-new-variables) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Changing Existing Variables](tutorials/docs/05_mutate.qmd#changing-existing-variables) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Composite Scores](tutorials/docs/05_mutate.qmd#composite-scores) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Exercises](tutorials/docs/05_mutate.qmd#exercises) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Conditionals](tutorials/docs/05_mutate.qmd#conditionals) </td>
   <td style="text-align:left;"> [One-Variable Input](tutorials/docs/05_mutate.qmd#one-variable-input), [Multi-Variable Input](tutorials/docs/05_mutate.qmd#multi-variable-input) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Iteration](tutorials/docs/05_mutate.qmd#iteration) </td>
   <td style="text-align:left;"> [Exercises](tutorials/docs/05_mutate.qmd#exercises) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Quick Test: $\chi^2$](tutorials/docs/05_mutate.qmd#quick-test:-$\chi^2$) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Exercises](tutorials/docs/05_mutate.qmd#exercises) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="4"><td colspan="2" style="border-bottom: 1px solid;"><strong>06: Reproducible Linear Models</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [The Linear Model](tutorials/docs/06_lm.qmd#the-linear-model) </td>
   <td style="text-align:left;"> [Data and Codebook](tutorials/docs/06_lm.qmd#data-and-codebook), [One Predictor](tutorials/docs/06_lm.qmd#one-predictor), [Hierarchical Models](tutorials/docs/06_lm.qmd#hierarchical-models), [Assumptions Checks](tutorials/docs/06_lm.qmd#assumptions-checks), [Robust Models](tutorials/docs/06_lm.qmd#robust-models) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Exercises](tutorials/docs/06_lm.qmd#exercises) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Reproducible Analysis](tutorials/docs/06_lm.qmd#reproducible-analysis) </td>
   <td style="text-align:left;"> [Same Results](tutorials/docs/06_lm.qmd#same-results), [Correct Analysis](tutorials/docs/06_lm.qmd#correct-analysis) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Reproducible Reporting](tutorials/docs/06_lm.qmd#reproducible-reporting) </td>
   <td style="text-align:left;"> [Creating a Quarto Document](tutorials/docs/06_lm.qmd#creating-a-quarto-document), [Creating a Code Chunk](tutorials/docs/06_lm.qmd#creating-a-code-chunk), [Body Text](tutorials/docs/06_lm.qmd#body-text), [Reporting](tutorials/docs/06_lm.qmd#reporting), [Rendering](tutorials/docs/06_lm.qmd#rendering) </td>
  </tr>
  <tr grouplength="6"><td colspan="2" style="border-bottom: 1px solid;"><strong>07: Summarise</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Setup](tutorials/docs/07_summarise.qmd#setup) </td>
   <td style="text-align:left;"> [Packages](tutorials/docs/07_summarise.qmd#packages), [Data](tutorials/docs/07_summarise.qmd#data) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Summarising](tutorials/docs/07_summarise.qmd#summarising) </td>
   <td style="text-align:left;"> [Overall](tutorials/docs/07_summarise.qmd#overall), [By Group](tutorials/docs/07_summarise.qmd#by-group), [Multiple Variables](tutorials/docs/07_summarise.qmd#multiple-variables) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Exercises](tutorials/docs/07_summarise.qmd#exercises) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Formatting Tables](tutorials/docs/07_summarise.qmd#formatting-tables) </td>
   <td style="text-align:left;"> [Quarto to HTML/PDF](tutorials/docs/07_summarise.qmd#quarto-to-html/pdf), [Exporting](tutorials/docs/07_summarise.qmd#exporting) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Quick Test: Correlation](tutorials/docs/07_summarise.qmd#quick-test:-correlation) </td>
   <td style="text-align:left;"> [Visualisation](tutorials/docs/07_summarise.qmd#visualisation), [Testing Correlation](tutorials/docs/07_summarise.qmd#testing-correlation) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Exercises](tutorials/docs/07_summarise.qmd#exercises) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="8"><td colspan="2" style="border-bottom: 1px solid;"><strong>08: Visualisations</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> NA </td>
   <td style="text-align:left;"> [Data Visualisation Resources](tutorials/docs/08_dataviz.qmd#data-visualisation-resources), [What do UGs know?](tutorials/docs/08_dataviz.qmd#what-do-ugs-know?) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Setup](tutorials/docs/08_dataviz.qmd#setup) </td>
   <td style="text-align:left;"> [Packages](tutorials/docs/08_dataviz.qmd#packages), [Data](tutorials/docs/08_dataviz.qmd#data) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Grammar of Graphics](tutorials/docs/08_dataviz.qmd#grammar-of-graphics) </td>
   <td style="text-align:left;"> [Layers](tutorials/docs/08_dataviz.qmd#layers), [Mapping](tutorials/docs/08_dataviz.qmd#mapping), [Geoms, etc.](tutorials/docs/08_dataviz.qmd#geoms,-etc.) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Histograms and Density Plots](tutorials/docs/08_dataviz.qmd#histograms-and-density-plots) </td>
   <td style="text-align:left;"> [Adjusting Binwidth](tutorials/docs/08_dataviz.qmd#adjusting-binwidth), [Colour and Fill Manual](tutorials/docs/08_dataviz.qmd#colour-and-fill-manual), [Adjusting Axes with `scale_*()`](tutorials/docs/08_dataviz.qmd#adjusting-axes-with-`scale_*()`), [Adding a Theme](tutorials/docs/08_dataviz.qmd#adding-a-theme), [Splitting by Group](tutorials/docs/08_dataviz.qmd#splitting-by-group) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Barplots](tutorials/docs/08_dataviz.qmd#barplots) </td>
   <td style="text-align:left;"> [Position Dodge](tutorials/docs/08_dataviz.qmd#position-dodge), [Reordering Categories](tutorials/docs/08_dataviz.qmd#reordering-categories) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Raincloud and Violin Plots](tutorials/docs/08_dataviz.qmd#raincloud-and-violin-plots) </td>
   <td style="text-align:left;"> [Calculating Stats](tutorials/docs/08_dataviz.qmd#calculating-stats) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Scatterplots](tutorials/docs/08_dataviz.qmd#scatterplots) </td>
   <td style="text-align:left;"> [Line of Best Fit](tutorials/docs/08_dataviz.qmd#line-of-best-fit), [Colour and Fill Palette](tutorials/docs/08_dataviz.qmd#colour-and-fill-palette), [3D Plots](tutorials/docs/08_dataviz.qmd#3d-plots) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Reporting](tutorials/docs/08_dataviz.qmd#reporting) </td>
   <td style="text-align:left;"> [With Quarto](tutorials/docs/08_dataviz.qmd#with-quarto), [Exporting and Linking](tutorials/docs/08_dataviz.qmd#exporting-and-linking) </td>
  </tr>
  <tr grouplength="11"><td colspan="2" style="border-bottom: 1px solid;"><strong>09: Labelled Data and Qualtrics</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> NA </td>
   <td style="text-align:left;"> [Acknowledgements](tutorials/docs/09_qtrics.qmd#acknowledgements) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Qualtrics](tutorials/docs/09_qtrics.qmd#qualtrics) </td>
   <td style="text-align:left;"> [SAV Data](tutorials/docs/09_qtrics.qmd#sav-data), [Setting Up Qualtrics](tutorials/docs/09_qtrics.qmd#setting-up-qualtrics), [Library](tutorials/docs/09_qtrics.qmd#library), [Exporting Data](tutorials/docs/09_qtrics.qmd#exporting-data) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Setup](tutorials/docs/09_qtrics.qmd#setup) </td>
   <td style="text-align:left;"> [Packages](tutorials/docs/09_qtrics.qmd#packages), [Data](tutorials/docs/09_qtrics.qmd#data), [Codebook](tutorials/docs/09_qtrics.qmd#codebook) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Variable Names](tutorials/docs/09_qtrics.qmd#variable-names) </td>
   <td style="text-align:left;"> [Default Variable Names](tutorials/docs/09_qtrics.qmd#default-variable-names), [Renaming ](tutorials/docs/09_qtrics.qmd#renaming-) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Exercises: Names](tutorials/docs/09_qtrics.qmd#exercises:-names) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Labelled Data](tutorials/docs/09_qtrics.qmd#labelled-data) </td>
   <td style="text-align:left;"> [Working with Labels](tutorials/docs/09_qtrics.qmd#working-with-labels), [Variable Labels](tutorials/docs/09_qtrics.qmd#variable-labels), [Value Labels](tutorials/docs/09_qtrics.qmd#value-labels), [Missing Values](tutorials/docs/09_qtrics.qmd#missing-values) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Exercises: Labels](tutorials/docs/09_qtrics.qmd#exercises:-labels) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Data Dictionaries](tutorials/docs/09_qtrics.qmd#data-dictionaries) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Converting Variables](tutorials/docs/09_qtrics.qmd#converting-variables) </td>
   <td style="text-align:left;"> [Factors](tutorials/docs/09_qtrics.qmd#factors), [Numeric](tutorials/docs/09_qtrics.qmd#numeric), [Efficient Conversion](tutorials/docs/09_qtrics.qmd#efficient-conversion) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Exercise: Conversion and Wrangling](tutorials/docs/09_qtrics.qmd#exercise:-conversion-and-wrangling) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Well done!](tutorials/docs/09_qtrics.qmd#well-done!) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="8"><td colspan="2" style="border-bottom: 1px solid;"><strong>10: Putting it all together</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> NA </td>
   <td style="text-align:left;"> [Reproducibility Certification](tutorials/docs/10_reproducibility.qmd#reproducibility-certification) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Setup](tutorials/docs/10_reproducibility.qmd#setup) </td>
   <td style="text-align:left;"> [Packages](tutorials/docs/10_reproducibility.qmd#packages), [Data](tutorials/docs/10_reproducibility.qmd#data) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Reproducibility Report: Part One](tutorials/docs/10_reproducibility.qmd#reproducibility-report:-part-one) </td>
   <td style="text-align:left;"> [Section 1: Reproducibility of Data Processing](tutorials/docs/10_reproducibility.qmd#section-1:-reproducibility-of-data-processing), [Section 2: Reproducibility of Analysis Environment](tutorials/docs/10_reproducibility.qmd#section-2:-reproducibility-of-analysis-environment), [Section 3: Reproducibility of Analysis Pipeline](tutorials/docs/10_reproducibility.qmd#section-3:-reproducibility-of-analysis-pipeline) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [ANOVA Speedrun ](tutorials/docs/10_reproducibility.qmd#anova-speedrun-) </td>
   <td style="text-align:left;"> [One-Way ANOVA](tutorials/docs/10_reproducibility.qmd#one-way-anova), [Factorial Designs](tutorials/docs/10_reproducibility.qmd#factorial-designs), [Mixed Designs](tutorials/docs/10_reproducibility.qmd#mixed-designs) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Reproducibility Report: Part Two](tutorials/docs/10_reproducibility.qmd#reproducibility-report:-part-two) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Exercises](tutorials/docs/10_reproducibility.qmd#exercises) </td>
   <td style="text-align:left;"> [Option 1: Continue working](tutorials/docs/10_reproducibility.qmd#option-1:-continue-working), [Option 2: Work on one of your own projects](tutorials/docs/10_reproducibility.qmd#option-2:-work-on-one-of-your-own-projects), [Option 3: Conduct a reproducibility check on a published study ](tutorials/docs/10_reproducibility.qmd#option-3:-conduct-a-reproducibility-check-on-a-published-study-) </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Submitting Your Work](tutorials/docs/10_reproducibility.qmd#submitting-your-work) </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> [Final Thoughts](tutorials/docs/10_reproducibility.qmd#final-thoughts) </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
</table>

## Index of Functions

Looking for a function you can't quite remember how to use? You're in the right place!
The table below is arranged alphabetically by function name, and the linked full name (including relevant package calls) will take you to the help documentation.

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Function Name </th>
   <th style="text-align:left;"> Link to Help Documentation </th>
   <th style="text-align:left;"> Used In... </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> across() </td>
   <td style="text-align:left;"> <a href="https://dplyr.tidyverse.org/reference/across.html">dplyr::across()</a> </td>
   <td style="text-align:left;"> 07: Summarise<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> all() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/all.html">all()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select </td>
  </tr>
  <tr>
   <td style="text-align:left;"> anova() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/stats/anova.html">anova()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models </td>
  </tr>
  <tr>
   <td style="text-align:left;"> any() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/any.html">any()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select </td>
  </tr>
  <tr>
   <td style="text-align:left;"> apa_print() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/pkg/papaja/man/apa_print.html">papaja::apa_print()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> apa_table() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/pkg/papaja/man/apa_table.html">papaja::apa_table()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> arrange() </td>
   <td style="text-align:left;"> <a href="https://dplyr.tidyverse.org/reference/arrange.html">dplyr::arrange()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select </td>
  </tr>
  <tr>
   <td style="text-align:left;"> as.character() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/character.html">as.character()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models </td>
  </tr>
  <tr>
   <td style="text-align:left;"> as.factor() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/factor.html">as.factor()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models </td>
  </tr>
  <tr>
   <td style="text-align:left;"> as.numeric() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/numeric.html">as.numeric()</a> </td>
   <td style="text-align:left;"> 01: IntRoduction </td>
  </tr>
  <tr>
   <td style="text-align:left;"> as_tibble() </td>
   <td style="text-align:left;"> <a href="https://tibble.tidyverse.org/reference/as_tibble.html">tibble::as_tibble()</a> </td>
   <td style="text-align:left;"> 09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> autoplot() </td>
   <td style="text-align:left;"> <a href="https://ggplot2.tidyverse.org/reference/autoplot.html">ggplot2::autoplot()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models </td>
  </tr>
  <tr>
   <td style="text-align:left;"> between() </td>
   <td style="text-align:left;"> <a href="https://dplyr.tidyverse.org/reference/between.html">dplyr::between()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select </td>
  </tr>
  <tr>
   <td style="text-align:left;"> boxplot() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/graphics/boxplot.html">boxplot()</a> </td>
   <td style="text-align:left;"> 03: Datasets </td>
  </tr>
  <tr>
   <td style="text-align:left;"> c() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/c.html">c()</a> </td>
   <td style="text-align:left;"> 01: IntRoduction<br>02: IntRoduction II<br>03: Datasets<br>04: Filter and Select<br>05: Mutate<br>06: Reproducible Linear Models<br>07: Summarise<br>09: Labelled Data and Qualtrics<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> c_across() </td>
   <td style="text-align:left;"> <a href="https://dplyr.tidyverse.org/reference/c_across.html">dplyr::c_across()</a> </td>
   <td style="text-align:left;"> 05: Mutate </td>
  </tr>
  <tr>
   <td style="text-align:left;"> cat() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/cat.html">cat()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models </td>
  </tr>
  <tr>
   <td style="text-align:left;"> chisq.test() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test()</a> </td>
   <td style="text-align:left;"> 05: Mutate </td>
  </tr>
  <tr>
   <td style="text-align:left;"> class() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/class.html">class()</a> </td>
   <td style="text-align:left;"> 01: IntRoduction<br>06: Reproducible Linear Models </td>
  </tr>
  <tr>
   <td style="text-align:left;"> contains() </td>
   <td style="text-align:left;"> <a href="https://tidyselect.r-lib.org/reference/starts_with.html">dplyr::contains()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select<br>07: Summarise<br>09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> contr.sum() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/stats/contrast.html">contr.sum()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> contrasts() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/stats/contrasts.html">contrasts()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> cor.test() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/stats/cor.test.html">cor.test()</a> </td>
   <td style="text-align:left;"> 07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> correlation() </td>
   <td style="text-align:left;"> <a href="https://easystats.github.io/correlation/reference/correlation.html">correlation::correlation()</a> </td>
   <td style="text-align:left;"> 07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> count() </td>
   <td style="text-align:left;"> <a href="https://dplyr.tidyverse.org/reference/count.html">dplyr::count()</a> </td>
   <td style="text-align:left;"> 03: Datasets<br>04: Filter and Select<br>05: Mutate </td>
  </tr>
  <tr>
   <td style="text-align:left;"> data() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/utils/data.html">data()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models </td>
  </tr>
  <tr>
   <td style="text-align:left;"> deframe() </td>
   <td style="text-align:left;"> <a href="https://tibble.tidyverse.org/reference/enframe.html">tibble::deframe()</a> </td>
   <td style="text-align:left;"> 07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> describe_distribution() </td>
   <td style="text-align:left;"> <a href="https://easystats.github.io/datawizard/reference/describe_distribution.html">datawizard::describe_distribution()</a> </td>
   <td style="text-align:left;"> 03: Datasets </td>
  </tr>
  <tr>
   <td style="text-align:left;"> detach() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/detach.html">detach()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> drop_na() </td>
   <td style="text-align:left;"> <a href="https://tidyr.tidyverse.org/reference/drop_na.html">tidyr::drop_na()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select </td>
  </tr>
  <tr>
   <td style="text-align:left;"> emmeans() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans::emmeans()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> everything() </td>
   <td style="text-align:left;"> <a href="https://tidyselect.r-lib.org/reference/everything.html">dplyr::everything()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select </td>
  </tr>
  <tr>
   <td style="text-align:left;"> factor() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/factor.html">factor()</a> </td>
   <td style="text-align:left;"> 01: IntRoduction<br>05: Mutate<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> filter() </td>
   <td style="text-align:left;"> <a href="https://dplyr.tidyverse.org/reference/filter.html">dplyr::filter()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select<br>05: Mutate </td>
  </tr>
  <tr>
   <td style="text-align:left;"> geom_histogram() </td>
   <td style="text-align:left;"> <a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">ggplot2::geom_histogram()</a> </td>
   <td style="text-align:left;"> 08: Visualisations </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ggpairs() </td>
   <td style="text-align:left;"> <a href="https://ggobi.github.io/ggally/reference/ggpairs.html">GGally::ggpairs()</a> </td>
   <td style="text-align:left;"> 07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ggscatmat() </td>
   <td style="text-align:left;"> <a href="https://ggobi.github.io/ggally/reference/ggscatmat.html">GGally::ggscatmat()</a> </td>
   <td style="text-align:left;"> 07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> glance() </td>
   <td style="text-align:left;"> <a href="https://generics.r-lib.org/reference/glance.html">broom::glance()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> glimpse() </td>
   <td style="text-align:left;"> <a href="https://pillar.r-lib.org/reference/glimpse.html">dplyr::glimpse()</a> </td>
   <td style="text-align:left;"> 03: Datasets </td>
  </tr>
  <tr>
   <td style="text-align:left;"> gsub() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/grep.html">gsub()</a> </td>
   <td style="text-align:left;"> 07: Summarise<br>09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> here() </td>
   <td style="text-align:left;"> <a href="https://here.r-lib.org//reference/here.html">here::here()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select<br>05: Mutate<br>06: Reproducible Linear Models<br>07: Summarise<br>08: Visualisations<br>09: Labelled Data and Qualtrics<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> hist() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/graphics/hist.html">hist()</a> </td>
   <td style="text-align:left;"> 03: Datasets </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ifelse() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/ifelse.html">ifelse()</a> </td>
   <td style="text-align:left;"> 08: Visualisations </td>
  </tr>
  <tr>
   <td style="text-align:left;"> install.packages() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/utils/install.packages.html">install.packages()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> installed.packages() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/utils/installed.packages.html">installed.packages()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> invisible() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/invisible.html">invisible()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> is.character() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/character.html">is.character()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select </td>
  </tr>
  <tr>
   <td style="text-align:left;"> is.na() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/NA.html">is.na()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select<br>09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> is.null() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/NULL.html">is.null()</a> </td>
   <td style="text-align:left;"> 09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> joint_tests() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/pkg/emmeans/man/joint_tests.html">emmeans::joint_tests()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> kable_classic() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/pkg/kableExtra/man/kable_classic.html">kableExtra::kable_classic()</a> </td>
   <td style="text-align:left;"> 07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> kable_styling() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kableExtra::kable_styling()</a> </td>
   <td style="text-align:left;"> 03: Datasets<br>04: Filter and Select<br>05: Mutate<br>07: Summarise<br>08: Visualisations<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> lapply() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/lapply.html">lapply()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> levels() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/levels.html">levels()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models </td>
  </tr>
  <tr>
   <td style="text-align:left;"> library() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/library.html">library()</a> </td>
   <td style="text-align:left;"> 02: IntRoduction II<br>03: Datasets<br>04: Filter and Select<br>05: Mutate<br>06: Reproducible Linear Models<br>07: Summarise<br>08: Visualisations<br>09: Labelled Data and Qualtrics<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> lm() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/stats/lm.html">lm()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> lmRob() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/pkg/robust/man/lmRob.html">robust::lmRob()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models </td>
  </tr>
  <tr>
   <td style="text-align:left;"> max() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/Extremes.html">max()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select<br>07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> mean() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/mean.html">mean()</a> </td>
   <td style="text-align:left;"> 01: IntRoduction<br>02: IntRoduction II<br>03: Datasets </td>
  </tr>
  <tr>
   <td style="text-align:left;"> median() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/stats/median.html">median()</a> </td>
   <td style="text-align:left;"> 02: IntRoduction II<br>03: Datasets<br>04: Filter and Select </td>
  </tr>
  <tr>
   <td style="text-align:left;"> min() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/Extremes.html">min()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select </td>
  </tr>
  <tr>
   <td style="text-align:left;"> model_parameters() </td>
   <td style="text-align:left;"> <a href="https://easystats.github.io/parameters/reference/model_parameters.html">parameters::model_parameters()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> mutate() </td>
   <td style="text-align:left;"> <a href="https://dplyr.tidyverse.org/reference/mutate.html">dplyr::mutate()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models </td>
  </tr>
  <tr>
   <td style="text-align:left;"> na_values() </td>
   <td style="text-align:left;"> <a href="https://larmarange.github.io/labelled/reference/na_values.html">labelled::na_values()</a> </td>
   <td style="text-align:left;"> 09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> names() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/names.html">names()</a> </td>
   <td style="text-align:left;"> 03: Datasets<br>07: Summarise<br>09: Labelled Data and Qualtrics<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ncol() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/nrow.html">ncol()</a> </td>
   <td style="text-align:left;"> 03: Datasets </td>
  </tr>
  <tr>
   <td style="text-align:left;"> nrow() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/nrow.html">nrow()</a> </td>
   <td style="text-align:left;"> 03: Datasets<br>04: Filter and Select </td>
  </tr>
  <tr>
   <td style="text-align:left;"> options() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/options.html">options()</a> </td>
   <td style="text-align:left;"> 08: Visualisations </td>
  </tr>
  <tr>
   <td style="text-align:left;"> paste() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/paste.html">paste()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> paste0() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/paste.html">paste0()</a> </td>
   <td style="text-align:left;"> 09: Labelled Data and Qualtrics<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> pick() </td>
   <td style="text-align:left;"> <a href="https://dplyr.tidyverse.org/reference/pick.html">dplyr::pick()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select </td>
  </tr>
  <tr>
   <td style="text-align:left;"> plot() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a> </td>
   <td style="text-align:left;"> 03: Datasets </td>
  </tr>
  <tr>
   <td style="text-align:left;"> position_jitterdodge() </td>
   <td style="text-align:left;"> <a href="https://ggplot2.tidyverse.org/reference/position_jitterdodge.html">ggplot2::position_jitterdodge()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> print() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/print.html">print()</a> </td>
   <td style="text-align:left;"> 07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> pull() </td>
   <td style="text-align:left;"> <a href="https://dplyr.tidyverse.org/reference/pull.html">dplyr::pull()</a> </td>
   <td style="text-align:left;"> 03: Datasets<br>05: Mutate<br>07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> range() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/range.html">range()</a> </td>
   <td style="text-align:left;"> 02: IntRoduction II<br>03: Datasets </td>
  </tr>
  <tr>
   <td style="text-align:left;"> rd() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/pkg/weights/man/rd.html">weights::rd()</a> </td>
   <td style="text-align:left;"> 02: IntRoduction II </td>
  </tr>
  <tr>
   <td style="text-align:left;"> read_csv() </td>
   <td style="text-align:left;"> <a href="https://readr.tidyverse.org/reference/read_delim.html">readr::read_csv()</a> </td>
   <td style="text-align:left;"> 03: Datasets<br>04: Filter and Select<br>05: Mutate<br>06: Reproducible Linear Models<br>07: Summarise<br>08: Visualisations<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> read_sav() </td>
   <td style="text-align:left;"> <a href="https://haven.tidyverse.org/reference/read_spss.html">haven::read_sav()</a> </td>
   <td style="text-align:left;"> 09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> report() </td>
   <td style="text-align:left;"> <a href="https://easystats.github.io/report/reference/report.html">report::report()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select<br>06: Reproducible Linear Models<br>07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> return() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/function.html">return()</a> </td>
   <td style="text-align:left;"> 07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> rglwidget() </td>
   <td style="text-align:left;"> <a href="https://dmurdoch.github.io/rgl/dev/reference/rglwidget.html">rgl::rglwidget()</a> </td>
   <td style="text-align:left;"> 08: Visualisations </td>
  </tr>
  <tr>
   <td style="text-align:left;"> rnorm() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a> </td>
   <td style="text-align:left;"> 02: IntRoduction II<br>06: Reproducible Linear Models </td>
  </tr>
  <tr>
   <td style="text-align:left;"> round() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/Round.html">round()</a> </td>
   <td style="text-align:left;"> 02: IntRoduction II<br>03: Datasets<br>06: Reproducible Linear Models </td>
  </tr>
  <tr>
   <td style="text-align:left;"> rowMeans() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/colSums.html">rowMeans()</a> </td>
   <td style="text-align:left;"> 05: Mutate </td>
  </tr>
  <tr>
   <td style="text-align:left;"> rowSums() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/colSums.html">rowSums()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select </td>
  </tr>
  <tr>
   <td style="text-align:left;"> rowid_to_column() </td>
   <td style="text-align:left;"> <a href="https://tibble.tidyverse.org/reference/rownames.html">tibble::rowid_to_column()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> rownames() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/colnames.html">rownames()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> scroll_box() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/pkg/kableExtra/man/scroll_box.html">kableExtra::scroll_box()</a> </td>
   <td style="text-align:left;"> 09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sd() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/stats/sd.html">sd()</a> </td>
   <td style="text-align:left;"> 03: Datasets<br>07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> select() </td>
   <td style="text-align:left;"> <a href="https://dplyr.tidyverse.org/reference/select.html">dplyr::select()</a> </td>
   <td style="text-align:left;"> 05: Mutate </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sessionInfo() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> set.seed() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/Random.html">set.seed()</a> </td>
   <td style="text-align:left;"> 02: IntRoduction II<br>06: Reproducible Linear Models<br>08: Visualisations </td>
  </tr>
  <tr>
   <td style="text-align:left;"> setdiff() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/sets.html">setdiff()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sqrt() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/MathFun.html">sqrt()</a> </td>
   <td style="text-align:left;"> 07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> starts_with() </td>
   <td style="text-align:left;"> <a href="https://tidyselect.r-lib.org/reference/starts_with.html">dplyr::starts_with()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select<br>05: Mutate<br>09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> str_to_sentence() </td>
   <td style="text-align:left;"> <a href="https://stringr.tidyverse.org/reference/case.html">stringr::str_to_sentence()</a> </td>
   <td style="text-align:left;"> 07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> str_to_title() </td>
   <td style="text-align:left;"> <a href="https://stringr.tidyverse.org/reference/case.html">stringr::str_to_title()</a> </td>
   <td style="text-align:left;"> 07: Summarise<br>08: Visualisations<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sub() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/grep.html">sub()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sum() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/sum.html">sum()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select<br>05: Mutate </td>
  </tr>
  <tr>
   <td style="text-align:left;"> summary() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/summary.html">summary()</a> </td>
   <td style="text-align:left;"> 03: Datasets<br>06: Reproducible Linear Models </td>
  </tr>
  <tr>
   <td style="text-align:left;"> t.test() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/stats/t.test.html">t.test()</a> </td>
   <td style="text-align:left;"> 01: IntRoduction<br>02: IntRoduction II<br>04: Filter and Select </td>
  </tr>
  <tr>
   <td style="text-align:left;"> theme_apa() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/pkg/papaja/man/theme_apa.html">papaja::theme_apa()</a> </td>
   <td style="text-align:left;"> 08: Visualisations<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> theme_minimal() </td>
   <td style="text-align:left;"> <a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">ggplot2::theme_minimal()</a> </td>
   <td style="text-align:left;"> 10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tidy() </td>
   <td style="text-align:left;"> <a href="https://generics.r-lib.org/reference/tidy.html">broom::tidy()</a> </td>
   <td style="text-align:left;"> 06: Reproducible Linear Models<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> to_factor() </td>
   <td style="text-align:left;"> <a href="https://larmarange.github.io/labelled/reference/to_factor.html">labelled::to_factor()</a> </td>
   <td style="text-align:left;"> 09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tolower() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/chartr.html">tolower()</a> </td>
   <td style="text-align:left;"> 07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> toupper() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/chartr.html">toupper()</a> </td>
   <td style="text-align:left;"> 07: Summarise </td>
  </tr>
  <tr>
   <td style="text-align:left;"> unclass() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/class.html">unclass()</a> </td>
   <td style="text-align:left;"> 09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ungroup() </td>
   <td style="text-align:left;"> <a href="https://dplyr.tidyverse.org/reference/group_by.html">dplyr::ungroup()</a> </td>
   <td style="text-align:left;"> 05: Mutate<br>09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> unlist() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/unlist.html">unlist()</a> </td>
   <td style="text-align:left;"> 09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> user_na_to_na() </td>
   <td style="text-align:left;"> <a href="https://larmarange.github.io/labelled/reference/na_values.html">labelled::user_na_to_na()</a> </td>
   <td style="text-align:left;"> 09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> val_label() </td>
   <td style="text-align:left;"> <a href="https://larmarange.github.io/labelled/reference/val_labels.html">labelled::val_label()</a> </td>
   <td style="text-align:left;"> 09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> val_labels() </td>
   <td style="text-align:left;"> <a href="https://larmarange.github.io/labelled/reference/val_labels.html">labelled::val_labels()</a> </td>
   <td style="text-align:left;"> 09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> var_label() </td>
   <td style="text-align:left;"> <a href="https://larmarange.github.io/labelled/reference/var_label.html">labelled::var_label()</a> </td>
   <td style="text-align:left;"> 09: Labelled Data and Qualtrics </td>
  </tr>
  <tr>
   <td style="text-align:left;"> where() </td>
   <td style="text-align:left;"> <a href="https://tidyselect.r-lib.org/reference/where.html">dplyr::where()</a> </td>
   <td style="text-align:left;"> 04: Filter and Select<br>10: Putting it all together </td>
  </tr>
  <tr>
   <td style="text-align:left;"> which() </td>
   <td style="text-align:left;"> <a href="https://rdrr.io/r/base/which.html">which()</a> </td>
   <td style="text-align:left;"> 07: Summarise </td>
  </tr>
</tbody>
</table>
